name: Pure GitHub Auto Scraper & Storage

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube Video/Live Link Dalein'
        required: true
        default: 'https://www.youtube.com/live/...'
      start_time:
        description: 'Scraping kab shuru karein? (24-Hour format me dalein jaise 08:02 ya 19:30 ya turant ke liye now likhein)'
        required: true
        default: 'now'

permissions:
  contents: write

env:
  TZ: 'Asia/Kolkata'

jobs:
  scrape_and_store:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install requests pandas

      - name: Run Scraper Script In Live Loop
        run: python scraper.py "${{ github.event.inputs.video_url }}" "${{ github.event.inputs.start_time }}"
