name: Continuous Live Chat Scraper

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube Live Stream URL Daaliye'
        required: true
        default: ''

permissions:
  contents: write

jobs:
  scrape_live:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install requests pandas

      - name: Run Infinite Scraper Loop
        run: python scraper.py "${{ github.event.inputs.video_url }}"
